### ISSUE TITLE
Language should fallback to EN if system language is not available

### ISSUE THREAD

**Issue by fkaelberer** [Vortezz/molkky-count#8]
Hi Vortezz,

thanks a for providing this free and privacy friendly app.

When first launching the app on a device with German system language, all text fields were labeled with their translation keys and not with localized text.

If the system language is not available, the app should default to English, as the translation keys often don't fit in the text fields which makes the app hard to use.

**Comment by Vortezz** [comment]
Hello fkaelberer, I will fix this right now!

Thanks a lot for the report :)

**Comment by Vortezz** [comment]
The issue has been resolved and the app will be updated as soon as possible!

Thanks a lot again, and have nice games :)
